### PR TITLE
Introduce Interactor for map creation

### PR DESCRIPTION
**Pull request by cpytel**
Introduces the Interactor gem and uses it to organize the actions that take
place after map creation.

### CODE REVIEW

**Comment by jdbann** [comment]
How does it feel to work with?

**Comment by cpytel** [comment]
It feels ok to work with. It's a lot of code and specs to clean up a few lines.

However, I can also see how if you make your Interactors fine-grained enough, that you can reuse them in other Organizers, so UpdateMap and DeleteMap will reuse some of the Interactors introduced here.

Have you used this before on a production app?

**Comment by jdbann** [comment]
> It's a lot of code and specs to clean up a few lines.

Yeah, it definitely seems like a long-winded way to refactor here.

> However, I can also see how if you make your Interactors fine-grained enough, that you can reuse them in other Organizers, so UpdateMap and DeleteMap will reuse some of the Interactors introduced here.

My hope was that they could also be reused in the Channels as well.

> Have you used this before on a production app?

No, I haven't. I've fought for them as a way to tidy up some heavy business logic which had a need to roll-back if later actions failed, but it was abandoned after I left that company.

I've always liked the approach and the clear individual chunks of logic. But the shapeless `context` object isn't my favourite idea.

**Comment by cpytel** [comment]
Well, I'm totally up for trying it out. We can always change if we're not liking it.

I agree about the channels, but when a channel does multiple things. What is best to do?

Take this, for example: https://github.com/tableparty/table/blob/d5059e11f6d09fc01c1e099e3786791fd2c2fcbb/app/channels/campaign_channel.rb#L16-L17

```
campaign.update(current_map: map)
CampaignChannel.broadcast_current_map(campaign)
```

Should we be introducing another organizer, or just call the interactors directly?

**Comment by jdbann** [comment]
> Should we be introducing another organizer, or just call the interactors directly?

I'm not sure. The interactor idea is that the controller doesn't care what happens, just whether it succeeded or failed. In the channels, we cannot do anything different with that response so it's just a way to coordinate logic. If the logic isn't complicated enough to need coordination then maybe we don't need the organizer?

They made a lot more sense when I was imagining a version of this which still functioned if the websocket connection wasn't possible. There you would have XHR and cable versions of the same thing.

**Comment by cpytel** [comment]
@jdbann check out a849fe6. In this commit, I separate the two broadcasts into their own interactors, and I introduce a new Organizer called `ChangeCurrentMap`, which uses `SetCurrentMap` and `BroadcastCurrentMap`.

Then, the existing Organizer uses `ChangeCurrentMap` (an organizer calling an organizer) and then finishes with `BroadcastMapSelector`.

One nice thing about this is that the conditional around broadcasting the current map disappears - each organizer knows whether it needs to broadcast the current map.

I'm comfortable continuing to push on using Interactor if you'd like. We can always change it if it turns out we don't like it.

**Comment by jdbann** [comment]
> Then, the existing Organizer uses ChangeCurrentMap (an organizer calling an organizer) and then finishes with BroadcastMapSelector.

Nice! They have the same API so should be pretty much interchangeable.

> I'm comfortable continuing to push on using Interactor if you'd like. We can always change it if it turns out we don't like it.

Yeah, let's give these a proper try and see how it feels. It might take a bit of time to find how granular we need to go. Currently they're only one action per interactor but `BroadcastCurrentMap` should probably always happen if you `SetCurrentMap`.

**Pull request merged**
